#include <gtest/gtest.h>

#include "test_helper.h"

#include "math_test.h"
#include "vr_test.h"
#include "tag_test.h"
#include "tag_mask_test.h"
#include "multi_vr_test.h"
#include "vm_test.h"
#include "uid_test.h"
#include "string_test.h"
#include "regex_string_test.h"
#include "age_test.h"
#include "date_test.h"
#include "time_test.h"
#include "date_time_test.h"
#include "json_test.h"
#include "visitor_test.h"
#include "randomizer_test.h"
#include "anonymizer_test.h"
#include "pathname_test.h"
#include "undefined_length_remover_test.h"
#include "dicom/data_element_test.h"
#include "dicom/data_set_test.h"
#include "dicom/sop_class_test.h"
#include "dicom/transfer_syntax_test.h"
#include "manipulators/padded_string_manipulator_test.h"
#include "manipulators/fixed_size_element_manipulator_test.h"
#include "manipulators/age_string_manipulator_test.h"
#include "manipulators/attribute_tag_manipulator_test.h"
#include "manipulators/code_string_manipulator_test.h"
#include "manipulators/date_manipulator_test.h"
#include "manipulators/date_time_manipulator_test.h"
#include "manipulators/decimal_string_manipulator_test.h"
#include "manipulators/floating_point_double_manipulator_test.h"
#include "manipulators/floating_point_manipulator_test.h"
#include "manipulators/integer_string_manipulator_test.h"
#include "manipulators/long_string_manipulator_test.h"
#include "manipulators/long_text_manipulator_test.h"
#include "manipulators/other_byte_manipulator_test.h"
#include "manipulators/other_double_manipulator_test.h"
#include "manipulators/other_float_manipulator_test.h"
#include "manipulators/other_long_manipulator_test.h"
#include "manipulators/other_word_manipulator_test.h"
#include "manipulators/person_name_manipulator_test.h"
#include "manipulators/short_string_manipulator_test.h"
#include "manipulators/short_text_manipulator_test.h"
#include "manipulators/signed_long_manipulator_test.h"
#include "manipulators/signed_short_manipulator_test.h"
#include "manipulators/time_manipulator_test.h"
#include "manipulators/unique_identifier_manipulator_test.h"
#include "manipulators/unknown_manipulator_test.h"
#include "manipulators/unlimited_characters_manipulator_test.h"
#include "manipulators/unlimited_text_manipulator_test.h"
#include "manipulators/unsigned_long_manipulator_test.h"
#include "manipulators/unsigned_short_manipulator_test.h"
#include "manipulators/uri_manipulator_test.h"
#include "manipulators/pixel_data_manipulator_test.h"
#include "dictionary/dictionary_test.h"
#include "zlib_test.h"
#include "dicom/file_test.h"

int main(int argc, char **argv) {
  vega::dictionary::Dictionary::set_dictionary(tests::path_to_file("dictionary.txt"));
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
